### ISSUE TITLE
Rebuild local code with docker

### ISSUE THREAD

**Issue by RMCampos** [d0x2f/retrograde.rs#18]
Hello!! Because I don't work with the Rust land daily, I'm using the docker option to build and run it locally.

Important note: I'm new in the Docker world. 

However, every time I made a change, I'm running the `docker build . --tag retrotools` command in order of creating a new and updated image. This command is creating more than one image. And this process takes several minutes. 

My question is: is it possible to update only the Docker image of the changed code and not create everything again?

Thanks in advance.

PS: I'm a very newbie.

**Comment by RMCampos** [comment]
Note: actually, is needed to rebuild the image when the code changes. When using a tag name, like in the above example, the build process is much faster. So I think we can close this issue.

**Comment by d0x2f** [comment]
Yeah, that's right, when you change the code it spends a lot of time compiling it. It's just how it is unfortunately.
